project:
  browser: edge
  urls:
   aurix_app: https://portal.mbos.mercedes-benz.com/software-container/container/ec844239-9088-46e5-a5c3-098247fffaea/overview
   aurix_fbl: https://portal.mbos.mercedes-benz.com/software-container/container/e243eaa9-c7f5-4116-b1ec-7c663d3f522c/overview
   
paths:
  data: data/testdata.xlsx
  locator: locators/locator.yaml
  screenshots: output/screenshots
selenium:
  implicit_wait: 0
  explicit_wait: 60
  page_load_timeout: 60
  poll_frequency: 0.5

pingid:
  exe_path: "C:/Program Files (x86)/Ping Identity/PingID/PingID.exe"
  window_title_keyword: "PingID"

  clean_start: true

  window:
    min_width: 520
    min_height: 320
    wait_timeout: 15

  clipboard:
    read_timeout: 3.0

runner:
  max_workers: 2

mail:
  enable: true

  smtp:
    host: smtp.qq.com
    port: 465
    use_ssl: true

  auth:
    username: botao_zhou@qq.com
    password: pyipbzmenzupbbhb

  sender:
    name: Selenium Automation
    address: botao_zhou@qq.com

  receivers:
    - thundersoft.a.zhou@mercedes-benz.com
    - botao_zhou@qq.com
